# Indicamos el lenguaje que estamos utilizando
language: node_js

# Utilizamos las versiones: 10, 12 y 14 que son las que actualmente estan manteniendose
node_js:
    - 10
    - 12
    - 14

# Instalamos las dependencias, mocha y grunt 
before_install:
  - npm install
  - npm install -g mocha
  - npm install -g grunt

# Ejecutamos los tests
script: grunt test