version: 2.1

# Define los trabajos que queremos que ejecute para este proyecto
jobs:

 build:
   
   docker:
      image: sergiocantero8/reserve-it
      
  # Indicamos que utilizamos Ubuntu
   machine: true
   steps:
      # Checkout del repositorio
      - checkout
      - run:
            name: Ejecutando tests
            command: grunt test
