version: 2.1

# Define los trabajos que queremos que ejecute para este proyecto

jobs:
 build:
  # Indicamos que utilizamos Ubuntu
   machine: true
   steps:
      # Checkout del repositorio
      - checkout

      # Descargamos y ejecutamos el contenedor Docker
      - run: docker pull sergiocantero8/reserve-it
      - run: docker run -t -v `pwd`:/test sergiocantero8/reserve-it:latest
